Add: 지원서 제출, 지원서 리스트 전체 출력 로직 작성 및 엔드포인트 구현.
wecode-bootcamp-korea/19-2nd-GetWanted-backend pull request #12
Opened 2021-04-30 09:45 UTC by deonii

- tests.py 작성 및 구동완료.
![](https://images.velog.io/images/deonii/post/2e493e08-660b-48e8-a373-026a638e44c2/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-04-30%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%206.42.54.png)

- 지원서 제출
![](https://images.velog.io/images/deonii/post/8fb5260d-f988-4bb2-a9ac-067b9499eb6e/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-04-30%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%206.43.51.png)

- 지원서 리스트 출력
![](https://images.velog.io/images/deonii/post/205c0458-af31-4506-a0df-b947bdeca148/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-04-30%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%206.44.01.png)

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-05-02 05:29 UTC, kst6294 requested changes
확인해주세요!

2021-05-02 05:29 UTC, kst6294 commented on users/utils.py
> +def get_applylist(user_id):
이 코드가 재사용 되나요?

2021-05-02 05:29 UTC, kst6294 commented on users/views.py
> +            notification_id = data['notification_id']
notification_id가 숫자 대신 문자나 혹은 특정한 다른 데이터가 들어오면 어떻개 되나요?

2021-05-02 06:15 UTC, deonii commented on users/utils.py
> +def get_applylist(user_id):
없습니다. views.py에 작성하겠습니다.

2021-05-02 06:19 UTC, deonii commented on users/views.py
> +            notification_id = data['notification_id']
에러상황 추가했습니다.

2021-05-03 01:39 UTC, kst6294 reviewed
1. apply 와 applylist get view 의 차이점에 대해서 정확히 알기가 어렵습니다!
2. apply 를 하기 위해서는 이력 정보나 지원 정보 등이 필요 할 것 같은데, 정작 post apply view 에서는 정작 어떠한 데이터도 받고 있지 않네요.
3. 전체적으로 코드에 대해 봐주시고, 어떻게 동작하는지 로직 설명도 같이 부탁드립니다.

2021-05-03 01:39 UTC, kst6294 commented on users/views.py
> +class ApplylistView(View):
지원현황인가요?

2021-05-03 01:39 UTC, kst6294 commented on users/views.py
> +            return JsonResponse({'MESSAGE': "VALUE_ERROR"}, status=400)
혹시 공고 문에서 위쪽 상단에 나오는 지원하기를 눌렀을 때 동작하나요?

2021-05-03 01:39 UTC, kst6294 commented on users/views.py
> +                    } for applylist in applylists]
웹 개발자, 접수 등은 의도한 바 대로 작성되어 있나요?

2021-05-03 08:57 UTC, merged