Add: 소셜 로그인 구현(카카오, 네이버, 구글)
wecode-bootcamp-korea/19-2nd-GetWanted-backend pull request #18
Opened 2021-05-03 12:13 UTC by deonii

- 카카오

![](https://images.velog.io/images/deonii/post/33456d91-3457-4a52-8d5c-cac2de00236d/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-05-03%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%207.11.34.png)

 - 구글
![](https://images.velog.io/images/deonii/post/ee6a7478-a570-4663-9b56-5dcd8dac7d74/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-05-03%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%207.13.16.png)

 - 네이버

![](https://images.velog.io/images/deonii/post/e467e718-6b56-4efa-bf3e-7640414ced07/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-05-03%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%207.16.01.png)

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-05-03 15:47 UTC, Kang-kyunghun requested changes
3개의 소셜로그인 모두 잘못된 토큰 또는 만료된 토큰을 전달하게 되면 다른 응답을 줍니다. 이럴 때에 대한 예외 처리도 추가하면 좋을 것 같습니다.

2021-05-03 15:47 UTC, Kang-kyunghun commented on users/views.py
> +            if User.objects.get(email=email).is_social == 1:
.is_social이 booleanfield일 것 같은데 그러면 == 1을 굳이 안 쓰셔도 됩니다.
```suggestion
            if User.objects.get(email=email).is_social :
```

2021-05-04 05:04 UTC, deonii commented on users/views.py
> +            if User.objects.get(email=email).is_social == 1:
예외상황 추가했는데 만료된 토큰을 가지고있지 않아서 유효하지 않은 토큰으로 통일했습니다.
조건문 수정했습니다.

2021-05-04 09:40 UTC, redsaumon commented
conflict 해결해주세요.

2021-05-04 12:02 UTC, kst6294 reviewed
재유님! 너무 잘하셨습니다! 
작고 소중한 피드백 확인 바랍니다!

2021-05-04 12:02 UTC, kst6294 commented on users/views.py
> +            access_token = social_signin(user_name, user_email)
이 부분은 email 에 대해 validation 과정 인 것 같은데, access_token 으로 변수를 정하면 혼동이 올 수 있을것 같네요.
적절한 변수명으로 변경해주세요.
아래도 마찬가지 입니다.

2021-05-05 04:45 UTC, deonii commented on users/views.py
> +            access_token = social_signin(user_name, user_email)
네 변경했습니다.

2021-05-06 01:41 UTC, kst6294 commented
LGTM 👍

2021-05-06 01:41 UTC, merged