[19기 이병재] Add: resumes app ResumeView method get
wecode-bootcamp-korea/19-2nd-GetWanted-backend pull request #19
Opened 2021-05-03 12:33 UTC by redgpcmffld

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 이력서 불러오기 기능 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-작성한 이력서 불러오기 기능 추가
-작성할 이력서 기본 데이터 불러오기 기능 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-05-03 15:38 UTC, Kang-kyunghun requested changes

2021-05-03 15:38 UTC, Kang-kyunghun commented on resumes/views.py
공백 제거해 주세요.

2021-05-03 15:38 UTC, Kang-kyunghun commented on resumes/views.py
> +    @login_required
공백 추가해 주세요.

2021-05-03 15:38 UTC, Kang-kyunghun commented on resumes/views.py
> +
- 불피요한 공백 제거
- 코드 논리상 resume_id가 먼저 등장한다면, if 체이닝 없이도 코드가 구현 가능 할 것 같습니다. if 체이닝 줄어들면 같은 논리여도 가독성이 더 좋아지지 않을까요?

2021-05-03 22:38 UTC, redgpcmffld commented on resumes/views.py
<img width="479" alt="스크린샷 2021-05-04 오전 7 37 43" src="https://user-images.githubusercontent.com/76928178/116941961-a0144480-acab-11eb-9a0b-d42fb1602060.png">
경훈님 저 줄 맞추려고 띄운건데 이런 경우에는 
<img width="491" alt="스크린샷 2021-05-04 오전 7 38 25" src="https://user-images.githubusercontent.com/76928178/116942009-b91cf580-acab-11eb-9e34-f0af68413007.png">
이렇게 하는게 맞는건가요?

2021-05-03 22:45 UTC, redgpcmffld commented on resumes/views.py
> +
if 체이닝을 없애려고 resume_id가 없는 경우를  먼저 처리했습니다.
경훈님이 말씀하신 resume_id가 먼저 등장한다는 그림이 이게 맞나요?

2021-05-03 22:46 UTC, redgpcmffld commented on resumes/views.py
> +    @login_required
추가했습니다.

2021-05-04 01:15 UTC, kst6294 commented
같은 코드에 대해 pr이 두개 올라와있는 것 같네요. 확인해주세요!

2021-05-04 01:28 UTC, Kang-kyunghun requested changes

2021-05-04 01:28 UTC, Kang-kyunghun commented on resumes/views.py
아니요 위코드 코드 컨벤션 잘 읽어 보시기 바랍니다. import line은 맞추고 내가 만든 모듈끼리는 공백 없이 그냥 해주세요.

2021-05-04 01:28 UTC, Kang-kyunghun commented on resumes/views.py
> +        resume  = Resume.objects.get(id=resume_id)
```suggestion
            }
            return JsonResponse({'MESSAGE': 'SUCCESS', 'RESULTS': results}, status=200)
            
        if not Resume.objects.filter(id=resume_id).exists():
            return JsonResponse({'MESSAGE':'NOT_FOUND_RESUME'},status=404)
        
        resume  = Resume.objects.get(id=resume_id)
```

가독성을 위해 다음과 같이 공백을 추가하면 좋을 것 같습니다.

2021-05-04 01:30 UTC, redgpcmffld commented on resumes/views.py
아 넵 알겠습니다.

2021-05-04 02:06 UTC, redgpcmffld commented on resumes/views.py
> +        resume  = Resume.objects.get(id=resume_id)
수정했습니다.

2021-05-04 02:26 UTC, kst6294 reviewed
확인 바랍니다.

2021-05-04 02:26 UTC, kst6294 commented on resumes/views.py
> +                'endMonth'    : career.end_working.split('-')[-1],
이부분에 대한 통신결과가 없네요. 추가해주시고, 
datetime 부분은 strftime 확인하셔서 실제로 노출되어야 하는 양식에 맞게 수정해주세요.

2021-05-04 03:00 UTC, redgpcmffld commented on resumes/views.py
> +                'endMonth'    : career.end_working.split('-')[-1],
<img width="729" alt="스크린샷 2021-05-04 오전 11 59 18" src="https://user-images.githubusercontent.com/76928178/116956397-2a6e9f80-acd0-11eb-84ef-6a31f46bdbaa.png">
지금 날짜 저장하는 field가 datetime이 아니고 그냥 charfield여서 프론트와 얘기해서 저렇게 했습니다.

2021-05-04 08:40 UTC, kst6294 commented
LGTM 👍

2021-05-04 08:40 UTC, merged