[19기 이병재] Add: resumes app FileResumeView 추가
wecode-bootcamp-korea/19-2nd-GetWanted-backend pull request #24
Opened 2021-05-04 12:39 UTC by redgpcmffld

<img width="915" alt="스크린샷 2021-05-04 오후 9 36 05" src="https://user-images.githubusercontent.com/76928178/117004330-e657bb00-ad20-11eb-97b5-f4fd3afda3b1.png">
<img width="450" alt="스크린샷 2021-05-04 오후 9 38 10" src="https://user-images.githubusercontent.com/76928178/117004436-08513d80-ad21-11eb-8d61-935f77ab3429.png">

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 파일 업로드, 다운로드 기능 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-pdf file upload 기능 추가
-작성한 이력서 데이터 pdf file로 download 기능 추가
-업로드한 file 삭제 기능 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-05-05 11:41 UTC, Kang-kyunghun requested changes

2021-05-05 11:41 UTC, Kang-kyunghun commented on resumes/views.py
> +            file      = FileResume.objects.get(id=resume_id)
이 부분 혹시 트랜젝션으로 처리 되나요?? 없는 resume_id가 들어 갔을 때 어떻게 되는지 알고 싶습니다.

2021-05-05 11:41 UTC, Kang-kyunghun commented on resumes/views.py
> +    )
s3는 병재님만 사용하시나요? s3 셋팅 같은 경우 프로젝트 전반에서 사용될 수 있기 때문에 모듈화 하는 것이 좋아 보입니다.

2021-05-05 13:58 UTC, redgpcmffld commented on resumes/views.py
> +            file      = FileResume.objects.get(id=resume_id)
없는 아이디가 들어오면 404 띄우고 끝나지 않을까요...?

2021-05-05 13:59 UTC, redgpcmffld commented on resumes/views.py
> +    )
모듈화..시도는 해봤는데 실패하고 어차피 저만 사용할것 같아서 이렇게 했는데 다시 시도해보겠습니다

2021-05-05 23:38 UTC, redgpcmffld commented on resumes/views.py
> +            file      = FileResume.objects.get(id=resume_id)
아..전체를 트랜잭션 걸어놔서 문제될수 있겠네요 다시 봐보겠습니다

2021-05-06 01:52 UTC, redgpcmffld commented on resumes/views.py
> +            file      = FileResume.objects.get(id=resume_id)
수정했습니다.

2021-05-06 01:52 UTC, redgpcmffld commented on resumes/views.py
> +    )
수정했습니다.

2021-05-06 02:47 UTC, merged