Add: 구인공고 list views.py 작성완료
wecode-bootcamp-korea/19-2nd-GetWanted-backend pull request #6
Opened 2021-04-28 11:13 UTC by dnjs0718

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Add: 구인공고 list views.py 작성완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 'tag'라는 키가 있을 시 그에 해당하는 value를 받고 필터링 하기
- 아무것도 적용이 안될 시 공고 전부다 불러오기
- tag가 아닌 이상한 값이 들어올 때 key error 호출
- 태그에 대한 값이 들어왔지만 그 태그 id가 태그 테이블에 존재하지 않을때 404에러 호출 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [  ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

![image](https://user-images.githubusercontent.com/72373362/116394232-9e86ee80-a85d-11eb-8ab6-3557e94c2262.png)

2021-04-29 05:14 UTC, kst6294 reviewed
수정바랍니다! 👍

2021-04-29 05:14 UTC, kst6294 commented on companies/views.py
> +class NotificationlistView(View):
```suggestion
class NotificationView(View):
```

2021-04-29 05:14 UTC, kst6294 commented on companies/views.py
> +                    return JsonResponse({'MESSAGE':'KEY_ERROR'},status=400)
```suggestion
            if request.GET.keys():
                if 'tag' in request.GET.keys():
                    tag    = request.GET['tag']
                else:
                    return JsonResponse({'MESSAGE':'KEY_ERROR'},status=400) 
```

2021-04-29 05:14 UTC, kst6294 commented on companies/urls.py
> +>>>>>>> 9f6ad43 (Add: 구인공고 list views.py 작성완료)
conflict

2021-04-29 05:14 UTC, kst6294 commented on companies/views.py
> +            return JsonResponse({'notification' : notification, 'total' : len(notification)}, status = 200)
재연님!
Q객체 잘 사용해보셨군요! 👏 

그런데 tag 가 아닌 잘못된 query parameter 를 보냈을 경우 에러를 발생시키는 상황은 피해주세요.
 ```suggestion
        try:
            tag = None
            if request.GET.keys():
                if 'tag' in request.GET.keys():
                    tag    = request.GET['tag']
                else:
                    return JsonResponse({'MESSAGE':'KEY_ERROR'},status=400)    
```
예를 들어 프론트에서 'tag' 가 아닌 'category' 로 요청했다고 가정해봅시다.

현재와 같은 경우, 프론트는 서버로부터 에러에 대한 응답을 받게 됩니다. 여기서 재연님의 목적이 사용자에게 잘못된 요청이라는 것을 알려주는 것이 목적이라면, 프론트는 에러코드를 받은 이후 에러용 특정 페이지로 이동을 시키겠지요. 이 때 사용자는 불필요한 화면을 마주하게 됩니다. 
또 하나, 잘못된 요청(잘못된 query param) 을 보냈다 하더라도, product 의 리스트를 보여주는 것이 목적이라면, 프론트는 error 메시지를 받으면 다시 서버측에 product 리스트를 요청하겠지요. 즉 불필요한 요청을 한 번 더 발생시키게 됩니다.

이때는 error 발생 대신 None 을 받았을 때와 동일 하게 전체 리스트를 전달해주는 것이 적합합니다.

2021-04-29 12:23 UTC, dnjs0718 commented on companies/views.py
> +class NotificationlistView(View):
수정하였습니다!

2021-04-29 12:23 UTC, dnjs0718 commented on companies/views.py
> +                    return JsonResponse({'MESSAGE':'KEY_ERROR'},status=400)
수정하였습니다!

2021-04-29 12:23 UTC, dnjs0718 commented on companies/urls.py
> +>>>>>>> 9f6ad43 (Add: 구인공고 list views.py 작성완료)
conflict 해결 완료했습니다!

2021-04-29 12:24 UTC, dnjs0718 commented on companies/views.py
> +            return JsonResponse({'notification' : notification, 'total' : len(notification)}, status = 200)
확인햇습니다!
필터링을  하나만 구현하기 때문에 Q객체 -> filter 사용으로 바꿨습니다!!

2021-04-30 01:35 UTC, Kang-kyunghun requested changes

2021-04-30 01:35 UTC, Kang-kyunghun commented on companies/tests.py
> +            'company': 'asdasds'}], 'total': 3})
test code도 가독성 있게 바꿔주시면 좋을 것 같아요~!!

2021-04-30 01:35 UTC, Kang-kyunghun commented on companies/views.py
> +            'image'   : Image.objects.filter(notification_id=notification.id).first().image_url,
notification이랑 image가 연결 되어 있는 것으로 보이는데, Image 테이블에 다시 쿼리를 보내지 않고 notification을 통해서 image를 가져와 보세요.

2021-04-30 01:35 UTC, Kang-kyunghun commented on companies/views.py
> +            'area'    : notification.company.address[:2],
주소에서 슬라싱 한 이유가 있나요?

2021-04-30 01:37 UTC, Kang-kyunghun commented
재연님 그리고 PR 제목에 [19기 원재연] 이렇게 붙여주세요!

2021-04-30 01:40 UTC, dnjs0718 commented on companies/views.py
> +            'area'    : notification.company.address[:2],
![image](https://user-images.githubusercontent.com/72373362/116637940-2b39c580-a9a0-11eb-9f20-770d49bcccb3.png)
원티드 홈페이지에 지역으로 필터링 거는 기능이 있지만 저희는
지역 필터링을 구현하지 않고 구인 공고 리스트에 회사의 위치를 보여주고 싶어서 슬라이싱 했습니다!

2021-04-30 01:54 UTC, dnjs0718 commented on companies/tests.py
> +            'company': 'asdasds'}], 'total': 3})
수정했습니다!

2021-04-30 01:55 UTC, dnjs0718 commented on companies/views.py
> +            'image'   : Image.objects.filter(notification_id=notification.id).first().image_url,
불필요한 쿼리문 삭제 했습니다!

2021-04-30 07:43 UTC, kst6294 commented on companies/views.py
> +            'image'   : notification.image_set.all().first().image_url,
all() 이 꼭 필요한가요?

2021-04-30 07:43 UTC, kst6294 commented on companies/views.py
> +            'area'    : notification.company.address[:2],
현재와 같은 방법으로 진행한다면, 만약 지역명이 2자가 아닌, 3자일 때 문제가 발생할 수 있겠네요.
비록 필터링 하는 기능이 없다 하더라도 address 의 데이터를 슬라이싱 하는 것 보다는 지역에 해당하는 컬럼을 추가해서 회사의 지역이 어디인지 보여주는 것이 좋겠습니다.

2021-04-30 07:44 UTC, kst6294 commented
추가기능 구현중이라면, 해당하는 라벨만 남겨주세요!

2021-04-30 08:25 UTC, dnjs0718 commented on companies/views.py
> +            'image'   : notification.image_set.all().first().image_url,
all() 삭제했습니다!

2021-04-30 08:28 UTC, dnjs0718 commented
1차 프로젝트에는 django 내의 모듈 paginator를 작성하여 구현을 하였고 이번에는 paginator를 import하여 페이지네이션을 구현 해봤습니다!

2021-04-30 11:34 UTC, kst6294 commented
LGTM 👍

2021-04-30 11:34 UTC, merged