Add: resumes app ResumeView method post
wecode-bootcamp-korea/19-2nd-GetWanted-backend pull request #9
Opened 2021-04-29 12:38 UTC by redgpcmffld

-작성한 이력서 DB에 저장하는 기능 추가

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 이력서 작성 데이터 저장 기능 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이력서 신규 작성 기능 추가
- 작성 중인 이력서 수정 기능 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-  

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-04-30 01:38 UTC, Kang-kyunghun commented
- PR 제목 앞에 [19기 홍길동] 이렇게 붙여 주세요.
- conflict 해결 해주세요.

2021-05-02 05:22 UTC, kst6294 requested changes
postman 사용해서 통신 결과도 같이 보여주세요.

2021-05-02 05:22 UTC, kst6294 commented on resumes/views.py
> +class ResumeView(View):
이 코드의 동작에 대해 설명 해주세요.

2021-05-02 05:22 UTC, kst6294 commented on resumes/views.py
> +import json
컨벤션 맞춰서 모듈 구분 해주세요.

2021-05-02 06:29 UTC, redgpcmffld commented on resumes/views.py
> +import json
수정 했습니다.

2021-05-02 06:30 UTC, redgpcmffld commented on resumes/views.py
> +class ResumeView(View):
어떤 코드 말씀하시는걸까요..?

2021-05-02 06:42 UTC, kst6294 reviewed
확인해주세요 병재님!

2021-05-02 06:42 UTC, kst6294 commented on resumes/views.py
> +            careers_data = data.get('workInfo')
careers_data 에는 어떠한 데이터가 담기는 건가요?

2021-05-02 06:42 UTC, kst6294 commented on resumes/views.py
> +class ResumeView(View):
ResumeView 처리하는 내용을 전체적으로 말씀해주세요!

2021-05-02 06:42 UTC, kst6294 commented on resumes/views.py
> +                if careers_data:
careers_data 가 wrok exprience 인가요?

2021-05-02 06:42 UTC, kst6294 commented on resumes/views.py
> +                    for career in careers_data]
이 코드들의 동작에 대해 설명 한 번 해주시고! 자세한 피드백은 설명을 본 후에, 내일 현장에서 다시 이야기해보시죠!

2021-05-02 06:43 UTC, redgpcmffld commented on resumes/views.py
> +            careers_data = data.get('workInfo')
이력서에 들어가는 겅력사항들이 들어갑니다.
workInfo:
[
{companyName: "위코드"
details: "주요 성과"
id: 0
isWorking: "on"
position: "위코드"
startMonth: "12"
startYear: "2014"
},

{companyName: "위코드2"
details: "주요 성과2"
endMonth: "01"
endYear: "2017"
id: 1
position: "위코드2"
startMonth: "12"
startYear: "2014"
}
]

2021-05-02 06:44 UTC, redgpcmffld commented on resumes/views.py
> +                if careers_data:
맞습니다.

2021-05-02 07:33 UTC, redgpcmffld commented on resumes/views.py
> +                    for career in careers_data]
위의 코드는 작성 중인 이력서에 데이터를 넣는 상황이고 
경력사항이 있는지 없는지 체크를 한 후 있으면 경력사항이 담긴 리스트를 for문을 돌려서 db에 넣어주는 동작을 합니다.
프론트 쪽에서 재직 기간에 들어가는 날짜를 연도와 월을 따로 주기 때문에 받아서 합쳐주는 로직이 있습니다.
재직 중인지 아닌지가 isWorking이란 키에 들어오는데 체크를 안 하면 재직 상태값과 재직 종료 기간 키가 안 들어와서 초기값을 지정해주고 키가 들어오면 들어오는 값으로 입력해주는 로직이고 경력사항이 기존에 등록되있는게 있으면 update를 하고 없으면 새로 생성해주는 로직입니다. 초기값 지정해주는 키 들도 미입력시 안 들어오는 키값들입니다.
그리고 필수 값인 항목들은 .get으로 가져오지 않고 []로 가져오고 있습니다.

2021-05-02 07:52 UTC, redgpcmffld commented on resumes/views.py
> +                    for career in careers_data]
제가 생각을 잘못 한거 같은데 그냥 update_or_create로 바꿀수 있을 것 같습니다

2021-05-03 01:48 UTC, Kang-kyunghun requested changes

2021-05-03 01:48 UTC, Kang-kyunghun commented on resumes/tests.py
> +        self.assertEqual(response.status_code, 201)
status 코드만 확인하지 마시고, 결과 값도 확인해 주세요.

2021-05-03 01:48 UTC, Kang-kyunghun commented on resumes/views.py
> +                    'status':data.get('isFinal',0)
가독성과 위코드 코드 컨벤션에 맞게 수정해 주세요.

2021-05-03 01:48 UTC, Kang-kyunghun commented on resumes/tests.py
> +    def test_resume_create_success(self):
view 코드 상에 workInfo가 없어도 코드가 정상 작동 해야 됩니다. 이 경우도 test에 추가해 주세요.

2021-05-03 01:53 UTC, kst6294 commented on resumes/views.py
> +                    if career_data.get('isWorking') == 1:
isWorking 이 0과, 1 만 받게 된다면, 굳이 `==1` 과 같은 조건을 추가하지 않아도 될 것 같습니다! 
1 자체가 truthy 한 값이니까요!

2021-05-03 02:32 UTC, redgpcmffld commented on resumes/tests.py
> +        self.assertEqual(response.status_code, 201)
결과 값은 그냥 메세지라서 생략했는데 추가 하겠습니다.

2021-05-03 02:32 UTC, redgpcmffld commented on resumes/views.py
> +                    'status':data.get('isFinal',0)
넵 수정하겠습니다.

2021-05-03 02:32 UTC, redgpcmffld commented on resumes/tests.py
> +    def test_resume_create_success(self):
그럼 success case test 함수를 하나 더 만들어야 하는건가요?

2021-05-03 07:41 UTC, kst6294 reviewed
테스트코드 확인해주세요

2021-05-03 07:41 UTC, kst6294 commented on resumes/tests.py
> +        self.assertEqual(response.json(), {'MESSAGE': 'SUCCESS'})
단순히 message : success 뿐 아니라 아닌, 실제로 전달 되는 데이터도 메시지에 넣어주셔야 합니다!

2021-05-03 07:42 UTC, kst6294 commented
LGTM 👍

2021-05-03 07:43 UTC, merged